package cn.edu.zut.gradesign.bean.user;

import java.io.Serializable;

public class Clazz implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clazz.id
     *
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clazz.college
     *
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    private String college;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clazz.school_dis
     *
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    private String schoolDis;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clazz.academy
     *
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    private String academy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clazz.grade
     *
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    private String grade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clazz.clazz
     *
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    private String clazz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clazz.mail
     *
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    private String mail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clazz.site
     *
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    private String site;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clazz.city
     *
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clazz.address
     *
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clazz.info
     *
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    private String info;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clazz.exp
     *
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    private String exp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clazz.id
     *
     * @return the value of clazz.id
     *
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clazz.id
     *
     * @param id the value for clazz.id
     *
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clazz.college
     *
     * @return the value of clazz.college
     *
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    public String getCollege() {
        return college;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clazz.college
     *
     * @param college the value for clazz.college
     *
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    public void setCollege(String college) {
        this.college = college == null ? null : college.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clazz.school_dis
     *
     * @return the value of clazz.school_dis
     *
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    public String getSchoolDis() {
        return schoolDis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clazz.school_dis
     *
     * @param schoolDis the value for clazz.school_dis
     *
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    public void setSchoolDis(String schoolDis) {
        this.schoolDis = schoolDis == null ? null : schoolDis.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clazz.academy
     *
     * @return the value of clazz.academy
     *
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    public String getAcademy() {
        return academy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clazz.academy
     *
     * @param academy the value for clazz.academy
     *
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    public void setAcademy(String academy) {
        this.academy = academy == null ? null : academy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clazz.grade
     *
     * @return the value of clazz.grade
     *
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    public String getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clazz.grade
     *
     * @param grade the value for clazz.grade
     *
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    public void setGrade(String grade) {
        this.grade = grade == null ? null : grade.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clazz.clazz
     *
     * @return the value of clazz.clazz
     *
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    public String getClazz() {
        return clazz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clazz.clazz
     *
     * @param clazz the value for clazz.clazz
     *
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    public void setClazz(String clazz) {
        this.clazz = clazz == null ? null : clazz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clazz.mail
     *
     * @return the value of clazz.mail
     *
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    public String getMail() {
        return mail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clazz.mail
     *
     * @param mail the value for clazz.mail
     *
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    public void setMail(String mail) {
        this.mail = mail == null ? null : mail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clazz.site
     *
     * @return the value of clazz.site
     *
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    public String getSite() {
        return site;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clazz.site
     *
     * @param site the value for clazz.site
     *
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    public void setSite(String site) {
        this.site = site == null ? null : site.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clazz.city
     *
     * @return the value of clazz.city
     *
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clazz.city
     *
     * @param city the value for clazz.city
     *
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clazz.address
     *
     * @return the value of clazz.address
     *
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clazz.address
     *
     * @param address the value for clazz.address
     *
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clazz.info
     *
     * @return the value of clazz.info
     *
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    public String getInfo() {
        return info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clazz.info
     *
     * @param info the value for clazz.info
     *
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    public void setInfo(String info) {
        this.info = info == null ? null : info.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clazz.exp
     *
     * @return the value of clazz.exp
     *
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    public String getExp() {
        return exp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clazz.exp
     *
     * @param exp the value for clazz.exp
     *
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    public void setExp(String exp) {
        this.exp = exp == null ? null : exp.trim();
    }
}