package cn.edu.zut.gradesign.bean.user;

import java.io.Serializable;

public class Master implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master.id
     *
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master.authority
     *
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    private Integer authority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master.phone
     *
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master.ip
     *
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    private Integer ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master.os
     *
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    private Integer os;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master.mac
     *
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    private Integer mac;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master.password
     *
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master.mail
     *
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    private String mail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master.info
     *
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    private String info;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master.exp
     *
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    private String exp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master.id
     *
     * @return the value of master.id
     *
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master.id
     *
     * @param id the value for master.id
     *
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master.authority
     *
     * @return the value of master.authority
     *
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    public Integer getAuthority() {
        return authority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master.authority
     *
     * @param authority the value for master.authority
     *
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    public void setAuthority(Integer authority) {
        this.authority = authority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master.phone
     *
     * @return the value of master.phone
     *
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master.phone
     *
     * @param phone the value for master.phone
     *
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master.ip
     *
     * @return the value of master.ip
     *
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    public Integer getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master.ip
     *
     * @param ip the value for master.ip
     *
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    public void setIp(Integer ip) {
        this.ip = ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master.os
     *
     * @return the value of master.os
     *
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    public Integer getOs() {
        return os;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master.os
     *
     * @param os the value for master.os
     *
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    public void setOs(Integer os) {
        this.os = os;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master.mac
     *
     * @return the value of master.mac
     *
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    public Integer getMac() {
        return mac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master.mac
     *
     * @param mac the value for master.mac
     *
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    public void setMac(Integer mac) {
        this.mac = mac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master.password
     *
     * @return the value of master.password
     *
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master.password
     *
     * @param password the value for master.password
     *
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master.mail
     *
     * @return the value of master.mail
     *
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    public String getMail() {
        return mail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master.mail
     *
     * @param mail the value for master.mail
     *
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    public void setMail(String mail) {
        this.mail = mail == null ? null : mail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master.info
     *
     * @return the value of master.info
     *
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    public String getInfo() {
        return info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master.info
     *
     * @param info the value for master.info
     *
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    public void setInfo(String info) {
        this.info = info == null ? null : info.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master.exp
     *
     * @return the value of master.exp
     *
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    public String getExp() {
        return exp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master.exp
     *
     * @param exp the value for master.exp
     *
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    public void setExp(String exp) {
        this.exp = exp == null ? null : exp.trim();
    }
}