package cn.edu.zut.gradesign.bean.user;

import java.io.Serializable;

public class User implements Serializable ,Cloneable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.name
     *
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.phone
     *
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.mail
     *
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    private String mail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.stu_num
     *
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    private String stuNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_name
     *
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.college
     *
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    private String college;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.academy
     *
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    private String academy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.grade
     *
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    private String grade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.clazz
     *
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    private String clazz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.city
     *
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.address
     *
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.info
     *
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    private String info;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.start_date
     *
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    private String startDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.end_date
     *
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    private String endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.date
     *
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    private String date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.year
     *
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    private Integer year;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.exp
     *
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    private String exp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.name
     *
     * @return the value of user.name
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.name
     *
     * @param name the value for user.name
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.phone
     *
     * @return the value of user.phone
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.phone
     *
     * @param phone the value for user.phone
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.mail
     *
     * @return the value of user.mail
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    public String getMail() {
        return mail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.mail
     *
     * @param mail the value for user.mail
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    public void setMail(String mail) {
        this.mail = mail == null ? null : mail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.stu_num
     *
     * @return the value of user.stu_num
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    public String getStuNum() {
        return stuNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.stu_num
     *
     * @param stuNum the value for user.stu_num
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    public void setStuNum(String stuNum) {
        this.stuNum = stuNum == null ? null : stuNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_name
     *
     * @return the value of user.user_name
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_name
     *
     * @param userName the value for user.user_name
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.college
     *
     * @return the value of user.college
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    public String getCollege() {
        return college;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.college
     *
     * @param college the value for user.college
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    public void setCollege(String college) {
        this.college = college == null ? null : college.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.academy
     *
     * @return the value of user.academy
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    public String getAcademy() {
        return academy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.academy
     *
     * @param academy the value for user.academy
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    public void setAcademy(String academy) {
        this.academy = academy == null ? null : academy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.grade
     *
     * @return the value of user.grade
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    public String getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.grade
     *
     * @param grade the value for user.grade
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    public void setGrade(String grade) {
        this.grade = grade == null ? null : grade.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.clazz
     *
     * @return the value of user.clazz
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    public String getClazz() {
        return clazz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.clazz
     *
     * @param clazz the value for user.clazz
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    public void setClazz(String clazz) {
        this.clazz = clazz == null ? null : clazz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.city
     *
     * @return the value of user.city
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.city
     *
     * @param city the value for user.city
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.address
     *
     * @return the value of user.address
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.address
     *
     * @param address the value for user.address
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.info
     *
     * @return the value of user.info
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    public String getInfo() {
        return info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.info
     *
     * @param info the value for user.info
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    public void setInfo(String info) {
        this.info = info == null ? null : info.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.start_date
     *
     * @return the value of user.start_date
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    public String getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.start_date
     *
     * @param startDate the value for user.start_date
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    public void setStartDate(String startDate) {
        this.startDate = startDate == null ? null : startDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.end_date
     *
     * @return the value of user.end_date
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    public String getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.end_date
     *
     * @param endDate the value for user.end_date
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    public void setEndDate(String endDate) {
        this.endDate = endDate == null ? null : endDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.date
     *
     * @return the value of user.date
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    public String getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.date
     *
     * @param date the value for user.date
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    public void setDate(String date) {
        this.date = date == null ? null : date.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.year
     *
     * @return the value of user.year
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    public Integer getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.year
     *
     * @param year the value for user.year
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    public void setYear(Integer year) {
        this.year = year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.exp
     *
     * @return the value of user.exp
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    public String getExp() {
        return exp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.exp
     *
     * @param exp the value for user.exp
     * @mbggenerated Tue Dec 21 18:17:06 CST 2021
     */
    public void setExp(String exp) {
        this.exp = exp == null ? null : exp.trim();
    }

    //声明为可克隆的
    @Override
    public Object clone() throws CloneNotSupportedException {
        return super.clone();
    }
}